# Generated by Django 4.2.15 on 2025-06-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('opening_female', models.IntegerField()),
                ('opening_male', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='breeder.flock')),
                ('start_date', models.DateField()),
                ('current_stage', models.CharField(default='Chick', max_length=20)),
                ('current_shed', models.CharField(default='Chick Shed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('stage', models.CharField(max_length=20)),
                ('shed', models.CharField(max_length=50)),
                ('opening_female', models.IntegerField()),
                ('female_mortality', models.IntegerField()),
                ('closing_female', models.IntegerField()),
                ('cumulative_female_mortality', models.IntegerField()),
                ('cumulative_female_mortality_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('opening_male', models.IntegerField()),
                ('male_mortality', models.IntegerField()),
                ('closing_male', models.IntegerField()),
                ('cumulative_male_mortality', models.IntegerField()),
                ('cumulative_male_mortality_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hatching_eggs', models.IntegerField()),
                ('pullet_eggs', models.IntegerField()),
                ('commercial_eggs', models.IntegerField()),
                ('crack_eggs', models.IntegerField()),
                ('waste_eggs', models.IntegerField()),
                ('total_eggs', models.IntegerField()),
                ('total_eggs_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hatching_egg_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('opening_female_feed_stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('female_feed_consumption', models.DecimalField(decimal_places=2, max_digits=8)),
                ('female_stock_in', models.DecimalField(decimal_places=2, max_digits=8)),
                ('closing_female_feed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('opening_male_feed_stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('male_feed_consumption', models.DecimalField(decimal_places=2, max_digits=8)),
                ('male_stock_in', models.DecimalField(decimal_places=2, max_digits=8)),
                ('closing_male_feed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breeder.flock')),
            ],
        ),
    ]
